server.port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?logger=com.mysql.cj.log.StandardLogger&profileSQL=true&useTimezone=true&serverTimezone=GMT%2B3
    username: root
    password: mySQLpass123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


spring.view.prefix: /WEB-INF/view/layouts
spring.view.suffix: .jspx
server:
  servlet:
    context-path: /

debug: true
trace: true
